// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task_1.Models;

#nullable disable

namespace Task_1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250505081639_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Task_1.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TodoItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Milk, Bread, Cheese, Eggs",
                            IsCompleted = false,
                            Title = "Buy groceries"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Living room, Kitchen, Bathroom",
                            IsCompleted = false,
                            Title = "Clean the house"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Complete the final draft",
                            IsCompleted = false,
                            Title = "Finish project report"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Weekly check-in",
                            IsCompleted = false,
                            Title = "Call mom"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Electricity, Internet, Water",
                            IsCompleted = false,
                            Title = "Pay bills"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
